image: node:lts-alpine

cache:
  paths:
    - node_modules/

stages:
  - upload
  - deploy

upload:
  stage: upload
  script:
    - apk add --update --no-cache pkgconfig autoconf automake libtool nasm build-base zlib-dev libjpeg-turbo-dev zlib
    - npm install
    - npm install -g gulp
    - npm install gulp
    - export AWS_ACCESS_KEY_ID="$(echo "$AWS_ACCESS_KEY_ID")"
    - export AWS_SECRET_ACCESS_KEY="$(echo "$AWS_SECRET_ACCESS_KEY")"
    - ls
    - pwd
    - gulp
  artifacts:
    when: on_success
    paths:
      - dist
    expire_in: 1h
  only:
    - master


deploy:
  stage: deploy
  script:
    - cd ../
    - apk add py-pip
    - pip install --user awscli
    - export PATH="$PATH:/root/.local/bin"
    - export AWS_ACCESS_KEY_ID="$(echo "$LOCAL_AWS_ACCESS_KEY_ID")"
    - export AWS_SECRET_ACCESS_KEY="$(echo "$LOCAL_AWS_SECRET_ACCESS_KEY")"
    - export AWS_DEFAULT_REGION=eu-central-1
    - export PACKAGE_NAME="$(echo $CI_PROJECT_NAME)_latest.tgz"
    - export META_FILE_NAME="$(echo $CI_PROJECT_NAME)_latest_meta.yaml"
    - tar -zcvf "$PACKAGE_NAME" "$CI_PROJECT_NAME"/packages/ "$CI_PROJECT_NAME"/category.rec
    - echo "datestamp:" $(date) > "$META_FILE_NAME"
    - echo "hash:" $(sha256sum $PACKAGE_NAME | cut -f1 -d " ") >> "$META_FILE_NAME"
    - aws s3 cp "$PACKAGE_NAME" s3://source-git-pantherx-org/
    - aws s3 cp "$META_FILE_NAME" s3://source-git-pantherx-org/
  only:
    - tags
  tags: [source]

