image: node:lts-alpine

stages:
  - upload

upload:
  stage: upload
  script:
    - apk add --update --no-cache pkgconfig autoconf automake libtool nasm build-base zlib-dev libjpeg-turbo-dev zlib
    - npm install
    - export AWS_ACCESS_KEY_ID="$(echo "$AWS_ACCESS_KEY_ID")"
    - export AWS_SECRET_ACCESS_KEY="$(echo "$AWS_SECRET_ACCESS_KEY")"
    - gulp
  artifacts:
    when: on_success
    paths:
      - dist
    expire_in: 1h
  only:
    - master
